# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('cod_agenda', models.IntegerField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('profissional', models.CharField(max_length=100, verbose_name='Profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('cod_atendimento', models.IntegerField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('cnh', models.CharField(max_length=11, verbose_name='CNH')),
                ('titulo', models.CharField(max_length=11, verbose_name='Titulo de eleitor')),
                ('certidao', models.CharField(max_length=100, verbose_name='Certidao de Nascimento')),
                ('schooling', models.CharField(max_length=20, verbose_name='Esolaridade')),
                ('professing', models.CharField(max_length=20, verbose_name='Profissão')),
                ('date', models.DateField(verbose_name='Nascimento')),
                ('appliance', models.CharField(max_length=100, verbose_name='Tipo de Aparelho')),
                ('deficient', models.IntegerField(verbose_name='Número de Deficientes')),
                ('income', models.FloatField(verbose_name='Renda Familiar')),
                ('home', models.CharField(max_length=10, verbose_name='Tipo de Moradia')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Profissoes',
            fields=[
                ('cod_client_prof', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('ramo', models.CharField(max_length=100, verbose_name='Ramo')),
                ('fantasia', models.CharField(max_length=100, verbose_name='Fantasia')),
                ('adress', models.TextField(verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('cod_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('cod_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('cod_esp', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('cod_hab', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('cod_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(max_length=10)),
                ('escolaridade', models.CharField(max_length=10, verbose_name='Escolaridade')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('cod_prof', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('adress', models.TextField(verbose_name='Endereco')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('date', models.DateField(verbose_name='Data de Nascimento')),
                ('cart_professional', models.CharField(max_length=100, verbose_name='Cart .Profissional')),
                ('cod_esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Profissoes',
            fields=[
                ('cod_prof', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('cod_telefone', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('cod_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
                ('cod_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Aparelho',
            fields=[
                ('cod_tipo_aparelho', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Atendimento',
            fields=[
                ('cod_tipo_atendimento', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Deficiencia',
            fields=[
                ('cod_tipo_deficiencia', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('login', models.CharField(max_length=10, verbose_name='Login')),
                ('password', models.CharField(max_length=10, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('cod_vagas', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('date', models.DateField(verbose_name='Data de Inclusão')),
                ('cod_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissional'),
        ),
        migrations.AddField(
            model_name='cliente_profissoes',
            name='cod_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissoes'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cod_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cod_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cod_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cod_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissional'),
        ),
    ]
