# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('profissional', models.CharField(max_length=100, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('cnh', models.CharField(max_length=11, verbose_name='CNH')),
                ('titulo', models.CharField(max_length=11, verbose_name='Titulo de eleitor')),
                ('certidao', models.CharField(max_length=100, verbose_name='Certidao de Nascimento')),
                ('schooling', models.CharField(max_length=20, verbose_name='Esolaridade')),
                ('professing', models.CharField(max_length=20, verbose_name='Profissão')),
                ('date', models.DateField(verbose_name='Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('appliance', models.CharField(max_length=100, verbose_name='Tipo de Aparelho')),
                ('deficient', models.IntegerField(verbose_name='Número de Deficientes')),
                ('income', models.FloatField(verbose_name='Renda Familiar')),
                ('home', models.CharField(max_length=10, verbose_name='Tipo de Moradia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Cliente_Profissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Cliente Profissao',
                'verbose_name_plural': 'Cliente Profissoes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('ramo', models.CharField(max_length=100, verbose_name='Ramo')),
                ('fantasia', models.CharField(max_length=100, verbose_name='Fantasia')),
                ('adress', models.TextField(verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('cod_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(max_length=10)),
                ('escolaridade', models.CharField(max_length=10, verbose_name='Escolaridade')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('adress', models.TextField(verbose_name='Endereco')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('date', models.DateField(verbose_name='Data de Nascimento')),
                ('cart_professional', models.CharField(max_length=100, verbose_name='Cart .Profissional')),
                ('cod_esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Especialidade')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('cod_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
                ('cod_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissional')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Aparelho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Tipo Aparelho',
                'verbose_name_plural': 'Tipo Aparelhos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo Atendimento',
                'verbose_name_plural': 'Tipo Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Deficiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Tipo Deficiencia',
                'verbose_name_plural': 'Tipo Deficiencias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('login', models.CharField(max_length=10, verbose_name='Login')),
                ('password', models.CharField(max_length=10, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date', models.DateField(verbose_name='Data de Inclusão')),
                ('cod_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='cod_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissional'),
        ),
        migrations.AddField(
            model_name='cliente_profissoes',
            name='cod_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissao'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cod_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cod_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cod_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cod_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissional'),
        ),
    ]
